evmosd tx staking create-validator \
  --amount=1000000aphoton \
  --pubkey=$(evmosd tendermint show-validator) \
  --moniker="denet" \
  --chain-id=evmos_9000-1 \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="1000000" \
  --gas="auto" \
  --gas-prices="0.025aevmos" \
  --from=mykey
